CREATE SEQUENCE TURISMO.SEQ_DEPARTAMENTO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE TURISMO.SEQ_INVENTARIO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE TURISMO.SEQ_MANTENCION
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE TURISMO.SEQ_INGRESOMULTA
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE TURISMO.SEQ_ADDRESERVASERVEX
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE TURISMO.SEQ_USERS
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE TURISMO.SEQ_SERV_EXTRA
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE TURISMO.SEQ_RESERVA
START WITH 1
INCREMENT BY 1
NOCACHE;
