-- DROP SEQUENCE TURISMO.SEQ_DEPARTAMENTO;
-- DROP SEQUENCE TURISMO.SEQ_INVENTARIO;
-- DROP SEQUENCE TURISMO.SEQ_MANTENCION;
-- DROP SEQUENCE TURISMO.SEQ_INGRESOMULTA;
-- DROP SEQUENCE TURISMO.SEQ_ADDRESERVASERVEX;
-- DROP SEQUENCE TURISMO.SEQ_USERS;
-- DROP SEQUENCE TURISMO.SEQ_SERV_EXTRA;
-- DROP SEQUENCE TURISMO.SEQ_RESERVA;
-- DROP SEQUENCE TURISMO.SEQ_RESERVASERVEX;
-- DROP SEQUENCE TURISMO.SEQ_TRANSPORT;

CREATE SEQUENCE TURISMO.SEQ_DEPARTAMENTO
START WITH 217
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE TURISMO.SEQ_INVENTARIO
START WITH 11
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE TURISMO.SEQ_MANTENCION
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE TURISMO.SEQ_INGRESOMULTA
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE TURISMO.SEQ_ADDRESERVASERVEX
START WITH 400
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE TURISMO.SEQ_USERS
START WITH 513
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE TURISMO.SEQ_SERV_EXTRA
START WITH 8
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE TURISMO.SEQ_RESERVA
START WITH 126
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE TURISMO.SEQ_RESERVASERVEX
START WITH 400
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE TURISMO.SEQ_TRANSPORT
START WITH 126
INCREMENT BY 1
NOCACHE;
