CREATE SEQUENCE TURISMO.SEQ_DEPARTAMENTO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE TURISMO.SEQ_INVENTARIO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE TURISMO.SEQ_MANTENCION
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE TURISMO.SEQ_INGRESOMULTA
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE TURISMO.SEQ_ADDRESERVASERVEX
START WITH 1
INCREMENT BY 1
NOCACHE;