CREATE OR REPLACE PROCEDURE TURISMO.spAddDepartment (
  nombre IN TURISMO.DEPARTAMENTO.NOM_DEPTO%TYPE,
  direccion IN TURISMO.DEPARTAMENTO.DIRECCION_DEPTO%TYPE,
  habitaciones IN TURISMO.DEPARTAMENTO.CANT_HABITACIONES%TYPE,
  estacionamientos IN TURISMO.DEPARTAMENTO.CANT_ESTACIONAMIENTOS%TYPE,
  banos IN TURISMO.DEPARTAMENTO.CANT_BANOS%TYPE,
  internet IN TURISMO.DEPARTAMENTO.INTERNET%TYPE,
  cable IN TURISMO.DEPARTAMENTO.CABLE%TYPE,
  calefaccion IN TURISMO.DEPARTAMENTO.CALEFACCION%TYPE,
  amoblado IN TURISMO.DEPARTAMENTO.AMOBLADO%TYPE,
  precio IN TURISMO.DEPARTAMENTO.PRECIO_DEPTO%TYPE,
  estado IN TURISMO.DEPARTAMENTO.ESTADO_DEPTO%TYPE,
  descripcion IN TURISMO.DEPARTAMENTO.DESCRIPCION_DEPTO%TYPE,
  comuna IN TURISMO.DEPARTAMENTO.COMUNA_ID_COMUNA%TYPE
) 
IS
    ID NUMBER;
 BEGIN
    SELECT SEQ_DEPARTAMENTO.NEXTVAL INTO ID FROM DUAL "d";
    INSERT INTO DEPARTAMENTO (ID_DEPTO, NOM_DEPTO, DIRECCION_DEPTO, CANT_HABITACIONES, CANT_ESTACIONAMIENTOS, CANT_BANOS, INTERNET, CABLE,
                CALEFACCION, AMOBLADO, PRECIO_DEPTO, ESTADO_DEPTO, DESCRIPCION_DEPTO,COMUNA_ID_COMUNA) 
                VALUES (ID,NOMBRE,DIRECCION,HABITACIONES,ESTACIONAMIENTOS,BANOS,INTERNET,CABLE,CALEFACCION,AMOBLADO,PRECIO,ESTADO,DESCRIPCION,COMUNA);
    COMMIT;
 END;
/

CREATE OR REPLACE PROCEDURE TURISMO.spAddInventory (
  nombre IN TURISMO.INVENTARIO.NOMBRE_OBJ%TYPE,
  descripcion IN TURISMO.INVENTARIO.DESC_OBJ%TYPE
) 
AS
  ID NUMBER;
BEGIN
  SELECT SEQ_INVENTARIO.NEXTVAL INTO ID FROM DUAL "d";
      INSERT INTO INVENTARIO (NOMBRE_OBJ, ID_OBJ, DESC_OBJ)
                  VALUES (NOMBRE,ID,DESCRIPCION);
      COMMIT;
END;
/

