CREATE OR REPLACE PROCEDURE TURISMO.spDeleteDepartments (
  ID IN TURISMO.DEPARTAMENTO.ID_DEPTO%TYPE
) 
AS
BEGIN
  DELETE DEPARTAMENTO WHERE ID_DEPTO = ID;
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line(sqlerrm);
END;
/
CREATE OR REPLACE PROCEDURE TURISMO.spDeleteInventoryDepartment (
ID IN TURISMO.DEPARTAMENTO_INVENTARIO.ID%TYPE
)
AS
BEGIN
  DELETE DEPARTAMENTO_INVENTARIO WHERE ID = ID;
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line(sqlerrm);
END;
/
