CREATE OR REPLACE PROCEDURE TURISMO.spDeleteDepartments (
  ID IN TURISMO.DEPARTAMENTO.ID_DEPTO%TYPE
 ) 
 AS
 BEGIN
  DELETE DEPARTAMENTO WHERE ID_DEPTO = ID;
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line(sqlerrm);
END;
/

CREATE OR REPLACE PROCEDURE TURISMO.spDeleteInventoryDepartment (
 ID IN TURISMO.DEPARTAMENTO_INVENTARIO.ID%TYPE
 )
 AS
 BEGIN
  DELETE DEPARTAMENTO_INVENTARIO "d" WHERE "d".ID = ID;
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
        dbms_output.put_line(sqlerrm);
END;
/

CREATE OR REPLACE PROCEDURE TURISMO.spDeleteServExtra (
  id TURISMO.SERVICIO_EXTRA.ID_SERV%TYPE
 )
 AS
 BEGIN
  DELETE FROM SERVICIO_EXTRA WHERE ID_SERV = ID;
  EXCEPTION 
  WHEN OTHERS THEN dbms_output.PUT_LINE(SQLERRM());
END;
/
