CREATE OR REPLACE PROCEDURE TURISMO.spUpdateDepartments (
  ID IN TURISMO.DEPARTAMENTO.ID_DEPTO%TYPE,
  nombre IN TURISMO.DEPARTAMENTO.NOM_DEPTO%TYPE,
  direccion IN TURISMO.DEPARTAMENTO.DIRECCION_DEPTO%TYPE,
  habitaciones IN TURISMO.DEPARTAMENTO.CANT_HABITACIONES%TYPE,
  estacionamientos IN TURISMO.DEPARTAMENTO.CANT_ESTACIONAMIENTOS%TYPE,
  banos IN TURISMO.DEPARTAMENTO.CANT_BANOS%TYPE,
  internet IN TURISMO.DEPARTAMENTO.INTERNET%TYPE,
  cable IN TURISMO.DEPARTAMENTO.CABLE%TYPE,
  calefaccion IN TURISMO.DEPARTAMENTO.CALEFACCION%TYPE,
  amoblado IN TURISMO.DEPARTAMENTO.AMOBLADO%TYPE,
  precio IN TURISMO.DEPARTAMENTO.PRECIO_DEPTO%TYPE,
  estado IN TURISMO.DEPARTAMENTO.ESTADO_DEPTO%TYPE,
  descripcion IN TURISMO.DEPARTAMENTO.DESCRIPCION_DEPTO%TYPE,
  comuna IN TURISMO.DEPARTAMENTO.COMUNA_ID_COMUNA%TYPE
) 
AS
BEGIN
  UPDATE DEPARTAMENTO SET NOM_DEPTO = NOMBRE,
                          DIRECCION_DEPTO = DIRECCION,
                          CANT_HABITACIONES = HABITACIONES,
                          CANT_ESTACIONAMIENTOS = ESTACIONAMIENTOS,
                          CANT_BANOS = BANOS,
                          INTERNET = INTERNET,
                          CABLE = CABLE,
                          CALEFACCION = CALEFACCION,
                          AMOBLADO = AMOBLADO,
                          PRECIO_DEPTO = PRECIO,
                          ESTADO_DEPTO = ESTADO,
                          DESCRIPCION_DEPTO = DESCRIPCION WHERE ID_DEPTO = ID; 
COMMIT;
END;
/
